services:
  - type: web
    name: ligma-stocks
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: API_KEY
        value: 8276ddd2e49644c6a1ecd35f979afb7f